//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 参数 {0} 与参数{1}不相等！ 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotEqual {
            get {
                return ResourceManager.GetString("ArgumentNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 {0} 不在集合{1}中！ 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotIn {
            get {
                return ResourceManager.GetString("ArgumentNotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 {0} 有等于 null 的对象！ 的本地化字符串。
        /// </summary>
        internal static string HasNullObject {
            get {
                return ResourceManager.GetString("HasNullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 {0} 不能为空或者空字符！ 的本地化字符串。
        /// </summary>
        internal static string IsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("IsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数的类型 {0} 不是类型 {1} 的子类！ 的本地化字符串。
        /// </summary>
        internal static string NotAssignableFrom {
            get {
                return ResourceManager.GetString("NotAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 {0} 没有包含任何对象！ 的本地化字符串。
        /// </summary>
        internal static string NotContainsAny {
            get {
                return ResourceManager.GetString("NotContainsAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的程序集{0}。当前应用程序尚未加载该程序集。 的本地化字符串。
        /// </summary>
        internal static string NotInAssemblies {
            get {
                return ResourceManager.GetString("NotInAssemblies", resourceCulture);
            }
        }
    }
}
